/*
    left join : 할인율
    
*/
SELECT CAR_ID, CAR_TYPE, FEE
FROM (
    SELECT 
        c.CAR_ID,
        c.CAR_TYPE,
        FLOOR(c.DAILY_FEE * 30 * (1 - dp.DISCOUNT_RATE / 100)) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR c
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp
        ON c.CAR_TYPE = dp.CAR_TYPE AND dp.DURATION_TYPE = '30일 이상'
    WHERE c.CAR_TYPE IN ('세단', 'SUV')
      AND c.CAR_ID NOT IN (
          SELECT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
          WHERE START_DATE <= DATE '2022-11-30'
            AND END_DATE >= DATE '2022-11-01'
      )
)
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;