-- TOP N 뽑기
-- 코드를 입력하세요
SELECT MP.MEMBER_NAME, 
       RR.REVIEW_TEXT, 
       TO_CHAR(RR.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE MP
JOIN REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE RR.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM (
        SELECT MEMBER_ID, 
               RANK() OVER (ORDER BY COUNT(*) DESC) AS RNK
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    )
    WHERE RNK = 1
)
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC;